defmodule AshJobs.Transformers.IntegrateStateMachine do
  @moduledoc """
  Generates state_machine DSL section if not already defined by user.

  This transformer creates a state machine configuration based on the workflow definition:
  - One state per workflow step
  - Terminal states: :completed, :failed, :cancelled
  - Transitions based on on_success/on_error routing
  - Initial state is the first step in the workflow

  If the user has already defined a state_machine section, this transformer skips generation
  to preserve user customization.

  ## Generated State Machine

  For a workflow like:
      workflow do
        step :load_order do
          on_success :validate_inventory
          on_error :handle_error
        end

        step :validate_inventory do
          on_success :completed
        end
      end

  Generates:
      state_machine do
        initial_states [:load_order]
        default_initial_state :load_order
        state_attribute :state

        transitions do
          transition :to_validate_inventory, from: :load_order, to: :validate_inventory
          transition :to_completed, from: :validate_inventory, to: :completed
        end
      end
  """

  use Spark.Dsl.Transformer

  def transform(dsl_state) do
    # Get workflow configuration
    workflow_steps = Spark.Dsl.Extension.get_entities(dsl_state, [:workflow])

    if workflow_steps && length(workflow_steps) > 0 do
      # Check if state_machine section already exists
      if has_state_machine_config?(dsl_state) do
        # User defined their own state_machine, skip generation
        {:ok, dsl_state}
      else
        # Generate state_machine configuration
        dsl_state = generate_state_machine(dsl_state, workflow_steps)
        {:ok, dsl_state}
      end
    else
      # No workflow defined, skip
      {:ok, dsl_state}
    end
  end

  defp has_state_machine_config?(dsl_state) do
    # Check if initial_states is configured (indicates state_machine section exists)
    initial_states =
      Spark.Dsl.Transformer.get_option(dsl_state, [:state_machine], :initial_states)

    initial_states != nil
  end

  defp generate_state_machine(dsl_state, workflow_steps) do
    # Get state_attribute from workflow section (defaults to :state)
    # Use Spark.Dsl.Transformer.get_option which is the correct function for transformers
    state_attr =
      Spark.Dsl.Transformer.get_option(dsl_state, [:workflow], :state_attribute) || :state

    # Determine initial state (first step)
    initial_state = List.first(workflow_steps).name

    # Set state_machine options
    dsl_state =
      Spark.Dsl.Transformer.set_option(dsl_state, [:state_machine], :initial_states, [
        initial_state
      ])

    dsl_state =
      Spark.Dsl.Transformer.set_option(
        dsl_state,
        [:state_machine],
        :default_initial_state,
        initial_state
      )

    dsl_state =
      Spark.Dsl.Transformer.set_option(dsl_state, [:state_machine], :state_attribute, state_attr)

    # Generate and add transitions
    generate_transitions(dsl_state, workflow_steps)
  end

  defp generate_transitions(dsl_state, workflow_steps) do
    # Collect all transitions from workflow steps
    # The transition action should be the step's action that performs the transition
    transitions =
      workflow_steps
      |> Enum.flat_map(fn step ->
        transitions = []

        # Add success transition - the step's action transitions from step state to on_success state
        transitions =
          if step.on_success do
            transition_data = %{
              action: step.action,
              from: step.name,
              to: step.on_success
            }

            [transition_data | transitions]
          else
            transitions
          end

        # Add error transition - error handler action transitions from step state to :failed
        # Note: Error handler actions are generated by GenerateErrorActions transformer
        transitions =
          if step.on_error do
            transition_data = %{
              action: step.on_error,
              from: step.name,
              to: :failed
            }

            [transition_data | transitions]
          else
            transitions
          end

        # Add complete transition - for error handler steps that complete to terminal state
        transitions =
          if step.on_complete do
            transition_data = %{
              action: step.action,
              from: step.name,
              to: step.on_complete
            }

            [transition_data | transitions]
          else
            transitions
          end

        transitions
      end)
      # Group transitions by {action, to} and combine their from states
      # This handles cases where multiple steps use the same error handler
      |> Enum.group_by(fn t -> {t.action, t.to} end, fn t -> t.from end)
      |> Enum.map(fn {{action, to}, froms} ->
        %{action: action, from: Enum.uniq(froms), to: to}
      end)

    # Add each transition by creating transition structs directly
    Enum.reduce(transitions, dsl_state, fn transition, acc_state ->
      # Create transition struct directly (similar to GenerateErrorActions approach)
      transition_entity = %AshStateMachine.Transition{
        action: transition.action,
        from: transition.from,
        to: transition.to
      }

      Spark.Dsl.Transformer.add_entity(
        acc_state,
        [:state_machine, :transitions],
        transition_entity
      )
    end)
  end
end
