defmodule AshJobs.TestRepo.Migrations.RuntimeDagWorkflows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:polling_dag_needs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:dependent_id, :uuid, null: false)
      add(:need_id, :uuid, null: false)
    end

    create table(:polling_dag_jobs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:polling_dag_needs) do
      modify(
        :dependent_id,
        references(:polling_dag_jobs,
          column: :id,
          name: "polling_dag_needs_dependent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :need_id,
        references(:polling_dag_jobs,
          column: :id,
          name: "polling_dag_needs_need_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:polling_dag_jobs) do
      add(:name, :text, null: false)
      add(:run_count, :bigint, null: false, default: 0)
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:dag_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:error_message, :text)
      add(:state, :text, null: false, default: "run_jobs")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:dag_needs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:dependent_id, :uuid, null: false)
      add(:need_id, :uuid, null: false)
    end

    create table(:dag_jobs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:dag_needs) do
      modify(
        :dependent_id,
        references(:dag_jobs,
          column: :id,
          name: "dag_needs_dependent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :need_id,
        references(:dag_jobs,
          column: :id,
          name: "dag_needs_need_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:dag_jobs) do
      add(:parent_id, :uuid, null: false)
      add(:name, :text, null: false)
      add(:run_count, :bigint, null: false, default: 0)
      add(:started_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:dag_jobs) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:state)
      remove(:completed_at)
      remove(:started_at)
      remove(:run_count)
      remove(:name)
      remove(:parent_id)
    end

    drop(constraint(:dag_needs, "dag_needs_dependent_id_fkey"))

    drop(constraint(:dag_needs, "dag_needs_need_id_fkey"))

    alter table(:dag_needs) do
      modify(:need_id, :uuid)
      modify(:dependent_id, :uuid)
    end

    drop(table(:dag_jobs))

    drop(table(:dag_needs))

    drop(table(:dag_runs))

    alter table(:polling_dag_jobs) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:state)
      remove(:completed_at)
      remove(:started_at)
      remove(:run_count)
      remove(:name)
    end

    drop(constraint(:polling_dag_needs, "polling_dag_needs_dependent_id_fkey"))

    drop(constraint(:polling_dag_needs, "polling_dag_needs_need_id_fkey"))

    alter table(:polling_dag_needs) do
      modify(:need_id, :uuid)
      modify(:dependent_id, :uuid)
    end

    drop(table(:polling_dag_jobs))

    drop(table(:polling_dag_needs))
  end
end
